# Generated by Django 2.2 on 2019-05-19 14:40

from django.db import migrations, models
import django.db.models.deletion
import ttests.models


class Migration(migrations.Migration):

    dependencies = [
        ('ttests', '0002_auto_20190506_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'managed': True, 'verbose_name': 'Одиноч. / множеств. / самост. ответ', 'verbose_name_plural': 'Одиноч. / множеств. / самост. ответы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_right',
            field=models.BooleanField(default=False, verbose_name='это правильный ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ttests.Question', verbose_name='для вопроса'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=300, verbose_name='текст ответа'),
        ),
        migrations.AlterField(
            model_name='associateanswer',
            name='left_side',
            field=models.CharField(max_length=300, verbose_name='левая часть'),
        ),
        migrations.AlterField(
            model_name='associateanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associate_answers', to='ttests.Question', verbose_name='для вопроса'),
        ),
        migrations.AlterField(
            model_name='associateanswer',
            name='right_side',
            field=models.CharField(blank=True, help_text='правая часть сопоставления может быть пустой', max_length=300, null=True, verbose_name='правая часть'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, max_length=1000, verbose_name='пояснение ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='mediafile',
            field=models.ImageField(blank=True, null=True, upload_to=ttests.models.Question.user_directory_path, verbose_name='картинка для вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='баллы за верный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ttests.Test', verbose_name='для теста'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='текст вопроса'),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='name',
            field=models.CharField(max_length=120, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='questions',
            field=models.ManyToManyField(related_name='tags', to='ttests.Question', verbose_name='для вопроса'),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='recommendation',
            field=models.TextField(help_text='рекомендации будут выведены тестируемому\t\t\t\t\t\t\tв конце теста, если он неправильно ответит на вопросы\t\t\t\t\t\t\tс этим тегом', max_length=2000, verbose_name='рекомендации'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, help_text='заполнять не обязательно, но это поможет\t\t\t\t\tпользователям лучше понять тематику теста', max_length=3500, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='img_description',
            field=models.ImageField(blank=True, help_text='картинка позволит быстрее найти тест', null=True, upload_to=ttests.models.Test.user_directory_path, verbose_name='картинка теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=False, help_text='после публикации тест станет доступен другим\t\t\t\t\tпользователям для прохождения. После публикации\t\t\t\t\tне желательно изменять тест (только удалять)', verbose_name='опубликовать?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_shuffle_q',
            field=models.BooleanField(default=False, help_text='вопросы будут идти не по порядку', verbose_name='перемешать вопросы?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='only_fully_correct',
            field=models.BooleanField(default=False, help_text='засчитывать только полностью верные ответы\t\t\t\t\t(для вопросов с множественными и ассоциативными ответами)\t\t\t\t\tиначе будет вычислен балл для частично правильных ответов', verbose_name='только 100% верные ответы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='show_q_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='пользователю будет показано столько вопросов.\t\t\t\t\tВ действительности тест может иметь больше вопросов', null=True, verbose_name='количество вопросов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Это позволит быстрее найти тест среди других.', related_name='tests', to='ttests.TestTag', verbose_name='теги для теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='testing_time',
            field=models.DurationField(blank=True, help_text='в формате ЧЧ:ММ:СС', null=True, verbose_name='время тестирования'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=140, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='testtag',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='testtag',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='название'),
        ),
    ]
