# Generated by Django 2.2 on 2019-06-12 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ttests.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tresults', '0005_auto_20190612_2209'),
        ('ttests', '0003_auto_20190519_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontag',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='tags', to='ttests.Question', verbose_name='для вопроса'),
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='test',
            name='show_q_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='пользователю будет показано столько вопросов.\t\t\t\t\tВ действительности тест может иметь больше вопросов', null=True, validators=[ttests.validators.min_length_1], verbose_name='количество вопросов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=140, verbose_name='название теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='последнее редактирование'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
