# Generated by Django 2.2 on 2019-05-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ttests', '0003_auto_20190519_1740'),
        ('tresults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=27)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testings', to='ttests.Question')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testings', to='ttests.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testings', to='ttests.User')),
            ],
            options={
                'verbose_name': 'Подробный результат тестирования',
                'verbose_name_plural': 'Подробные результаты тестирования',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveSmallIntegerField()),
                ('date_complition', models.DateTimeField(db_index=True)),
                ('date_start', models.DateTimeField(db_index=True)),
                ('questions_tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_results', to='ttests.QuestionTag')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_results', to='ttests.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_results', to='ttests.User')),
            ],
            options={
                'verbose_name': 'Краткий результат тестирования',
                'verbose_name_plural': 'Краткие результаты тестирования',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestingAssocAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_left_id', models.IntegerField()),
                ('answer_right_id', models.IntegerField()),
                ('testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associate_answers', to='tresults.Testing')),
            ],
            options={
                'verbose_name': 'Ассоциативный ответ пользователя',
                'verbose_name_plural': 'Ассоциативные ответы пользователя',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestingAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tresults.Testing')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
                'managed': True,
            },
        ),
    ]
