# Generated by Django 2.2 on 2019-05-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttests', '0003_auto_20190519_1740'),
        ('tresults', '0002_testing_testinganswer_testingassocanswer_testingresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingresult',
            name='questions_tags',
        ),
        migrations.AddField(
            model_name='testingresult',
            name='questions_tags',
            field=models.ManyToManyField(related_name='testings_results', to='ttests.QuestionTag'),
        ),
    ]
