# Generated by Django 2.2 on 2019-06-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tresults', '0003_auto_20190531_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='testing_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testings', to='tresults.TestingResult'),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='questions_tags',
            field=models.ManyToManyField(blank=True, related_name='testings_results', to='ttests.QuestionTag'),
        ),
    ]
