# Generated by Django 2.2 on 2019-06-12 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tresults', '0004_auto_20190602_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testingresult',
            options={'managed': True, 'verbose_name': ' Результат тестирования', 'verbose_name_plural': ' Результаты тестирования'},
        ),
        migrations.AlterField(
            model_name='testing',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testings', to='ttests.Question', verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='score',
            field=models.CharField(help_text='в формате набранный балл / максимальный балл', max_length=27, verbose_name='балл'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testings', to='ttests.Test', verbose_name='тест'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testings', to=settings.AUTH_USER_MODEL, verbose_name='тестируемый'),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='date_complition',
            field=models.DateTimeField(db_index=True, verbose_name='завершение тестирования'),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='date_start',
            field=models.DateTimeField(db_index=True, verbose_name='начало тестирования'),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='questions_tags',
            field=models.ManyToManyField(blank=True, help_text='рекомендации из этих тегов будут показаны пользователю', related_name='testings_results', to='ttests.QuestionTag', verbose_name='теги вопросов'),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='result',
            field=models.PositiveSmallIntegerField(verbose_name='итоговый балл'),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_results', to='ttests.Test', verbose_name='тест'),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_results', to=settings.AUTH_USER_MODEL, verbose_name='тестируемый'),
        ),
    ]
